// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WandioMobilePhones.Infrastructure;

namespace WandioMobilePhones.Infrastructure.Migrations
{
    [DbContext(typeof(PhoneDbContext))]
    [Migration("20200905114419_addSeed")]
    partial class addSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WandioMobilePhones.Domain.DomainObjects.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhoneMobileAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("PhoneMobileAggregateId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1852010e-d095-4468-a882-b481dc444501"),
                            PhotoUrl = "fb.com"
                        },
                        new
                        {
                            Id = new Guid("a6aa3c2c-80ff-4407-a10d-49aeb8966a3a"),
                            PhotoUrl = "fb.com"
                        });
                });

            modelBuilder.Entity("WandioMobilePhones.Domain.DomainObjects.PhoneMobileAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Memory")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Procesor")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("ScreenSizeAndResolution")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55dc3d14-5b55-4da2-9f69-b864a72c6cb2"),
                            Manufacturer = "Apple",
                            Memory = "32gb",
                            Name = "IPhone 10",
                            OS = "IOS",
                            Price = 1000m,
                            Procesor = "AppleI8Proccess",
                            ScreenSizeAndResolution = "500px",
                            Size = "XL",
                            Video = "youtube.com",
                            Weight = 200.5
                        },
                        new
                        {
                            Id = new Guid("135726ed-aede-48b7-849e-31350954613a"),
                            Manufacturer = "Apple",
                            Memory = "32gb",
                            Name = "IPhone 11",
                            OS = "IOS",
                            Price = 1500m,
                            Procesor = "AppleI8Proccess",
                            ScreenSizeAndResolution = "500px",
                            Size = "X",
                            Video = "youtube.com",
                            Weight = 200.5
                        },
                        new
                        {
                            Id = new Guid("22a5963f-327b-4c43-8d79-00a82375bd53"),
                            Manufacturer = "Samsung",
                            Memory = "64gb",
                            Name = "Galaxy",
                            OS = "Android",
                            Price = 500m,
                            Procesor = "SAMSUNGI8Proccess",
                            ScreenSizeAndResolution = "500px",
                            Size = "XL",
                            Video = "youtube.com",
                            Weight = 200.5
                        });
                });

            modelBuilder.Entity("WandioMobilePhones.Domain.DomainObjects.Image", b =>
                {
                    b.HasOne("WandioMobilePhones.Domain.DomainObjects.PhoneMobileAggregate", null)
                        .WithMany("Images")
                        .HasForeignKey("PhoneMobileAggregateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
